# -*- coding: utf-8 -*-
"""M1_SNB_MiniProject_2_Structured_Data_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmqQ7dSCK7ibfXaJ3URZxJz777yb_a19

# Advanced Certification Programme in AI and MLOps
## A programme by IISc and TalentSprint
### Mini-Project Notebook: Structured Data Classification

**DISCLAIMER:** THIS NOTEBOOK IS PROVIDED ONLY AS A REFERENCE SOLUTION NOTEBOOK FOR THE MINI-PROJECT. THERE MAY BE OTHER POSSIBLE APPROACHES/METHODS TO ACHIEVE THE SAME RESULTS.

## Problem Statement

To predict whether a patient has a heart disease.

## Learning Objectives

At the end of the experiment, you will be able to

* understand the Cleveland Clinic Foundation for Heart Disease dataset
* pre-process this dataset
* build a neural network architecture/model using Keras sequential or functional api
* perform model training
* perform inference on an unseen data
* build a Gradio interface for this application

## Introduction

This example demonstrates how to do structured data classification, starting from a raw
CSV file. Our data includes both numerical and categorical features. We will do preprocessing to normalize the numerical features and vectorize the categorical
ones.

### Dataset

[Our dataset](https://archive.ics.uci.edu/ml/datasets/heart+Disease) is provided by the
Cleveland Clinic Foundation for Heart Disease.
It's a CSV file with 303 rows. Each row contains information about a patient (a
**sample**), and each column describes an attribute of the patient (a **feature**). We
use the features to predict whether a patient has a heart disease (**binary
classification**).

Here's the description of each feature:

Column| Description| Feature Type
------------|--------------------|----------------------
Age | Age in years | Numerical
Sex | (1 = male; 0 = female) | Categorical
CP | Chest pain type (0, 1, 2, 3, 4) | Categorical
Trestbpd | Resting blood pressure (in mm Hg on admission) | Numerical
Chol | Serum cholesterol in mg/dl | Numerical
FBS | fasting blood sugar in 120 mg/dl (1 = true; 0 = false) | Categorical
RestECG | Resting electrocardiogram results (0, 1, 2) | Categorical
Thalach | Maximum heart rate achieved | Numerical
Exang | Exercise induced angina (1 = yes; 0 = no) | Categorical
Oldpeak | ST depression induced by exercise relative to rest | Numerical
Slope | Slope of the peak exercise ST segment | Numerical
CA | Number of major vessels (0-3) colored by fluoroscopy | Both numerical & categorical
Thal | 3 = normal; 6 = fixed defect; 7 = reversible defect | Categorical
Target | Diagnosis of heart disease (1 = true; 0 = false) | Target
"""

#@title Download the data
!wget -qq https://cdn.iisc.talentsprint.com/AIandMLOps/Datasets/heart.csv
print("Data Downloaded Successfuly!!")
!ls | grep '.csv'

"""## Grading = 10 Points

### Import Required Packages
"""

import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers

"""## Load the data and pre-process it [3 Marks]

### Load data into a Pandas dataframe

Hint:: pd.read_csv
"""

file_url = "/content/heart.csv"
df = pd.read_csv(file_url)

"""Check the shape of the dataset:"""

df.shape

"""Check the preview of a few samples:

Hint:: head()
"""

df.head()

"""Draw some inference from the data. What does the target column indicate?

The last column, "target", indicates whether the patient has a heart disease (1) or not
(0).

### Missing values
"""

# Check if any missing values is present
df.isna().sum()

"""### Show the unique values present in each categorical columns

- Remove the rows which has '1' and '2' as values in `thal` column
"""

df.columns

# Print the unique values present in each categorical columns

categorical_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'ca', 'thal']

print(f"{'Col_name':<10} Unique values")
print("="*40)
for col in categorical_cols:
    print(f"{col:<10} {df[col].unique()}")

# Print the unique values present in each categorical columns along with their counts

for col in categorical_cols:
    print(f"{col:<10} {df[col].value_counts()}")
    print("="*40)

"""- Remove the rows which has '1' and '2' as values in `thal` column"""

df[df['thal'] == '1']

df[df['thal'] == '2']

idx = [df[df['thal'] == '1'].index[0], df[df['thal'] == '2'].index[0]]
idx

df = df.drop(idx, axis=0)
df.shape

df['thal'].value_counts()

# Recheck the unique values present in each categorical columns

print(f"{'Col_name':<10} Unique values")
print("="*40)
for col in categorical_cols:
    print(f"{col:<10} {df[col].unique()}")

"""### Convert the categorical values present in `thal` column to numerical labels

Hint: Create a dictionary mapping
"""

thal_mapping = {'fixed': 0, 'normal': 1, 'reversible': 2}
df['thal'] = df['thal'].map(thal_mapping)

print(f"{'Col_name':<10} Unique values")
print("="*40)
for col in categorical_cols:
    print(f"{col:<10} {df[col].unique()}")

"""### Split the dataset into training and testing sets"""

from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=df['target'])

X_train.shape, X_test.shape, y_train.shape, y_test.shape

"""### Scale the numerical features"""

numerical_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope']

df[numerical_cols].head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

X_train.head()

"""## Building the model [3 Marks]

* Use tf.keras.layers.Input() for input layer
* Add dense layers
* Add dropout layers
* Add a classification layer at the end
"""

# Create model
model = keras.Sequential()
model.add(layers.Input((X_train.shape[1],)))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(1, activation='sigmoid'))

model.summary()

# Compile model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Perform training
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

# Performance on test set
model.evaluate(X_test, y_test)

"""## Inference on new data [1 Mark]

To get a prediction for a new sample, you can simply call `model.predict()`.
"""

# Inference on new data

sample = {
    "age": 60,
    "sex": 1,
    "cp": 1,
    "trestbps": 145,
    "chol": 233,
    "fbs": 1,
    "restecg": 2,
    "thalach": 150,
    "exang": 0,
    "oldpeak": 2.3,
    "slope": 3,
    "ca": 0,
    "thal": "fixed",
}

data = pd.DataFrame(sample, index=[0])

data['thal'] = data['thal'].map(thal_mapping)

data[numerical_cols] = scaler.transform(data[numerical_cols])

data

pred = model.predict(data, verbose=0)
label = 'Does not have disease' if np.argmax(pred)==0 else 'Has disease'
label

"""## Gradio Implementation [3 Marks]

Create a Gradio interface for this `Heart Disease Prediction` application. For the feature values given by the user as input, perform predcition using the trained model, and return the result back to user.

Make use of gradio elements such as Textbox, Radio buttons, etc.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install gradio

import gradio
import gradio as gr

data.head()

# UI - Input components
in_age = gradio.Textbox(lines=1, placeholder=None, value="34", label='Age of the patient in yrs')
in_sex = gradio.Radio(["Female", "Male"], type="index", label='Gender')
in_cp = gradio.Radio([0, 1, 2, 3, 4], type="value", label='Chest pain type')
in_trestbps = gradio.Textbox(lines=1, placeholder=None, value="120", label='Resting blood pressure (in mm Hg)')
in_chol = gradio.Textbox(lines=1, placeholder=None, value="236", label='Serum cholestoral in mg/dl')
in_fbs = gradio.Radio([0, 1], type="value", label='Fasting blood sugar > 120 mg/dl')
in_restecg = gradio.Radio([0, 1, 2], type="value", label='Resting electrocardiographic results')
in_thalach = gradio.Textbox(lines=1, placeholder=None, value="150", label='Maximum heart rate achieved')
in_exang = gradio.Radio([0, 1], type="value", label='Exercise induced angina')
in_oldpeak = gradio.Textbox(lines=1, placeholder=None, value="2.3", label='ST depression induced by exercise relative to rest')
in_slope = gradio.Radio([0, 1, 2], type="value", label='The slope of the peak exercise ST segment')
in_ca = gradio.Radio([0, 1, 2, 3], type="value", label='Number of major vessels (0-3) colored by flourosopy')
in_thal = gradio.Radio(["fixed", "normal", "reversible"], type="value", label='Thalium Stress Test result')

# UI - Output component
out_label = gradio.Textbox(type="text", label='Prediction', elem_id="out_textbox")

# Label prediction function

def get_output_label(in_age, in_sex, in_cp, in_trestbps, in_chol, in_fbs, in_restecg, in_thalach, in_exang, in_oldpeak, in_slope, in_ca, in_thal):
    input_df = pd.DataFrame({"age": [in_age],
                             "sex": [in_sex],
                             "cp": [in_cp],
                             "trestbps": [in_trestbps],
                             "chol": [in_chol],
                             "fbs": [in_fbs],
                             "restecg": [in_restecg],
                             "thalach": [in_thalach],
                             "exang": [in_exang],
                             "oldpeak": [in_oldpeak],
                             "slope": [in_slope],
                             "ca": [in_ca],
                             "thal": [in_thal]
    })

    input_df['thal'] = input_df['thal'].map(thal_mapping)
    input_df[numerical_cols] = scaler.transform(input_df[numerical_cols])
    pred = model.predict(input_df, verbose=0)
    label = 'Does not have disease' if np.argmax(pred)==0 else 'Has disease'
    return label

# Create Gradio interface object

iface = gradio.Interface(fn = get_output_label,
                         inputs = [in_age, in_sex, in_cp, in_trestbps, in_chol, in_fbs, in_restecg, in_thalach, in_exang, in_oldpeak, in_slope, in_ca, in_thal],
                         outputs = [out_label],
                         title = "Heart Disease Prediction",
                         description = "To predict whether a patient has a heart disease.",
                         flagging_mode = "never"
                         )

iface.launch(share=True)