# -*- coding: utf-8 -*-
"""M3_AST_04_Transformer_Encoder_C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iqa7KPLT-9M7GOWiD-J5xUecwGmDsQoA

# Advanced Certification Programme in AI and MLOps
## A Program by IISc and TalentSprint
### Assignment 4: Transformer Encoders, Self Attention

## Learning Objectives

At the end of the experiment, you will be able to:

* understand the big picture of transformers
* understand the concept of self attention
* explore transformer encoder and positional embedding
* train an encoder-only transformer model for text classification

### The Big Picture of Transformer

<center>
<img src= "https://cdn.iisc.talentsprint.com/AIandMLOps/Images/M5%20AST%205%20Big%20Picture.png" width=800px/>
</center>

Above is the entire architecture of transformer. A TextVectorization layer, Embedding layer, an Encoder and a Decoder.

Transformer architecture follows an encoder-decoder structure. The encoder, on the left-hand side, is tasked with mapping an input sequence to a sequence of continuous representations; the decoder, on the right-hand side, receives the output of the encoder together with the decoder output at the previous time step to generate an output sequence.

The Transformer architecture was originally designed for translation. In the encoder, the attention layers can use all the words in a sentence (since, as we just saw, the translation of a given word can be dependent on what is after as well as before it in the sentence). The decoder, however, works sequentially and can only pay attention to the words in the sentence that it has already translated (so, only the words before the word currently being generated). For example, when we have predicted the first three words of the translated target, we give them to the decoder which then uses all the inputs of the encoder to try to predict the fourth word.

To speed things up during training (when the model has access to target sentences), the decoder is fed the whole target, but it is not allowed to use future words (if it had access to the word at position 2 when trying to predict the word at position 2, the problem would not be very hard!). For instance, when trying to predict the fourth word, the attention layer will only have access to the words in positions 1 to 3.

**Encoder-only Transformer:**

<br>

<center>
<img src= "https://cdn.iisc.talentsprint.com/AIandMLOps/Images/M5_AST_05_Image1_Transformer.png" width=900px/>
</center>

In this assignment decoder will not form the topic of discussion, the main focus will be on the Transformer Encoder.
This has been discussed in detail in the later sections of this notebook.

## Dataset Description

The **IMDb Movie Reviews dataset** is a binary sentiment analysis dataset consisting of 50,000 reviews from the Internet Movie Database (IMDb) labeled as *positive* or *negative*. The dataset contains an even number of positive and negative reviews.

This dataset is processed and used in the later sections of this notebook.

### Setup Steps:
"""

#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "" #@param {type:"string"}

#@title Please enter your password (your registered phone number) to continue: { run: "auto", display-mode: "form" }
password = "" #@param {type:"string"}

#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "M3_AST_04_Transformer_Encoder_C" #name of the notebook

def setup():
#  ipython.magic("sx pip3 install torch")

    ipython.magic("sx curl -O https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz")
    ipython.magic("sx tar -xvzf aclImdb_v1.tar.gz")
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer" : Answer, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://aimlops-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer():
  try:
    if not Answer:
      raise NameError
    else:
      return Answer
  except NameError:
    print ("Please answer Question")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")

"""### Importing required packages"""

# Importing required libraries and modules

import numpy as np  # Used for numerical computations and array operations
import matplotlib.pyplot as plt  # For data visualization and plotting
import os, pathlib, shutil, random  # OS-related operations, file handling, and randomization utilities

# Importing TensorFlow and Keras modules
import tensorflow as tf  # Core machine learning framework
from tensorflow import keras  # High-level API for building and training models

# Importing specific layers and utilities from Keras
from tensorflow.keras import layers  # For defining neural network layers
from tensorflow.keras.layers import TextVectorization, Embedding, Dense  # Specific layers for text processing and dense layers
from tensorflow.keras.utils import text_dataset_from_directory  # Utility for loading text datasets from a directory

"""#  **Part A** : Text Pre-processing Before Transformer Block

## Processing the dataset using TextVectorization layer of keras

### Data Preparation

A pre-processed version of the IMDB dataset provided by Keras was used in the previous assignments.

Originally IMDB dataset contains the *train* and the *test* folders.
Here, the original dataset will be used and pre-processing related to it will be explored.
"""

# List subdirectories
!cd aclImdb && ls -d */

# Remove unnecessary folder
!rm -r aclImdb/train/unsup

# Check a sample review
!cat aclImdb/train/pos/4077_10.txt

"""### Create a validation directory and move 20% of the train data to it"""

# Move 20% of the training data to the validation folder

# Define base directory paths for the dataset
base_dir = pathlib.Path("aclImdb")  # Base directory containing the dataset
val_dir = base_dir / "val"  # Path to the validation directory
train_dir = base_dir / "train"  # Path to the training directory

# Iterate over the two categories: 'neg' (negative) and 'pos' (positive) reviews
for category in ("neg", "pos"):
    # Create corresponding subdirectories in the validation directory for each category
    os.makedirs(val_dir / category)

    # List all files in the training directory for the current category
    files = os.listdir(train_dir / category)

    # Shuffle the file list to ensure random selection of validation samples
    # random.Random(1337).shuffle(files)  # Uncomment this line to shuffle files. Commented here for deterministic behavior in demonstrations.

    # Calculate the number of files (20%) to move to the validation directory
    num_val_samples = int(0.2 * len(files))

    # Select the last `num_val_samples` files as the validation samples
    val_files = files[-num_val_samples:]

    # Move the selected validation files from the training directory to the validation directory
    for fname in val_files:
        shutil.move(train_dir / category / fname,  # Source file path
                    val_dir / category / fname)   # Destination file path

"""### Create batches of data using `text_dataset_from_directory`"""

# Create dataset using a utility function to load data from directories

batch_size = 32  # Define the batch size for processing the data

# Create training dataset from the directory
train_ds = text_dataset_from_directory(
    "aclImdb/train",  # Path to the training dataset
    batch_size=batch_size  # Specify the batch size
)

# Create validation dataset from the directory
val_ds = text_dataset_from_directory(
    "aclImdb/val",  # Path to the validation dataset
    batch_size=batch_size  # Specify the batch size
)

# Create test dataset from the directory
test_ds = text_dataset_from_directory(
    "aclImdb/test",  # Path to the test dataset
    batch_size=batch_size  # Specify the batch size
)

# Create a dataset containing only the review text (excluding labels)
text_only_train_ds = train_ds.map(
    lambda x, y: x  # Map function to extract only the input text (x) and discard labels (y)
)

# Explanation of the lambda function:
# - The dataset `train_ds` contains tuples `(x, y)` where `x` is the review text, and `y` is the label.
# - `lambda x, y: x` transforms each tuple by keeping only the review text (x) and ignoring the label (y).
# - This is useful for tasks such as adapting the TextVectorization layer where only the raw text input is needed.

# Q: Name other such utilities seen earlier?
# A: Examples of similar utilities include:
#    - `Dataset.from_tensor_slices()` for creating a dataset from raw data.
#    - `Dataset.map()` for applying transformations to datasets.
#    - `tf.data.Dataset.batch()` for batching datasets.

"""There are 20000, 5000, and 25000 records in train, validation, and test directories with two class as positive and negative."""

# Check shapes and data types of the training dataset

for inputs, targets in train_ds:  # Iterate through batches in the training dataset
    # Print the shape and data type of the input data
    print("inputs.shape:", inputs.shape)  # Shape of input data (batch size, input sequence length)
    print("inputs.dtype:", inputs.dtype)  # Data type of input data (usually string for raw text)

    # Print the shape and data type of the target labels
    print("targets.shape:", targets.shape)  # Shape of target labels (batch size,)
    print("targets.dtype:", targets.dtype)  # Data type of target labels (usually int for categorical labels)

    # Display a sample input and its corresponding target
    print("inputs[2]:", inputs[2])  # Third input review in the current batch
    print("targets[2]:", targets[2])  # Label for the third input review

    break  # Break after the first batch to avoid processing all data

"""### Create TextVectorization layer and adapt to dataset"""

# Vectorizing the data

# Define the parameters for text vectorization
max_length = 600  # Maximum sequence length (maximum number of tokens per review)
max_tokens = 20000  # Maximum vocabulary size (number of unique tokens)

# Create a TextVectorization layer for preprocessing text
text_vectorization = layers.TextVectorization(
    max_tokens=max_tokens,  # Vocabulary size (maximum number of unique tokens to learn)
    output_mode="int",  # Output tokenized sequences as integers
    output_sequence_length=max_length,  # Limit the output sequence to the maximum length
)

# Adapt the TextVectorization layer to the training data
text_vectorization.adapt(text_only_train_ds)  # Learn the vocabulary from the text data (ignoring labels)

"""# **Part B** : Building Encoder Transformer

Figure below shows the **Transformer Model Architecture** as per the paper ["**Attention Is All You Need**"](https://arxiv.org/pdf/1706.03762v6.pdf) .Here, we are going to implement **Encoder** and try to understand how it function. We are writing **'as per the paper'** to  mention this paper throughout this notebook. To completely understand the Encoder Transformer, it is imperative to understand Self Attention which is used inside Multi-head Attention. The data after passing the TextVectorization layer and Embedding layer will pass the Self Attention layer.
<br><br>
<center>
<img src= "https://cdn.extras.talentsprint.com/aiml/Experiment_related_data/Images/Transformer.png" width=750px/>

</center>

## Self Attention
The attention mechanism being depicted in the picture below can be understood as the attention scores highlighting the most important features of the cat so that it can be identified.

<center>
<img src= "https://cdn.iisc.talentsprint.com/AIandMLOps/Images/Attention%20scores%20pic.png" width=700px/>
</center>

Most of the popular language models does not have just the term 'BERT' in their name but an important techique called 'self-attention'. Transformer-based architectures, which are primarily used in modelling language understanding tasks, eschew recurrence in neural networks and instead trust entirely on self-attention mechanisms to draw global dependencies between inputs and outputs.

<center>
<img src= "https://cdn.iisc.talentsprint.com/AIandMLOps/Images/M5%20AST5%20Self%20Attention%20Scores.png" width=900px/>
</center>

outputs = sum(inputs * pairwise_scores(inputs, inputs))

According to the self attention scores which are depicted in the picture, the word 'train pays' more attention to station rather than other words in consideration such as 'on' or the.

The attention mechanism allows output to focus attention on input while producing output while the self-attention model allows inputs to interact with each other (i.e calculate attention of all other inputs wrt one input).

Inside each attention head is a **Scaled Dot Product Self-Attention** operation, the operation returns a Attention vector as given by equation below:

$$ Self Attention = softmax(\frac{x^{T}_i x_j}{\sqrt{d_k}})x_j $$

The term  **$x^{T}_i x_j$** is dot product of input vector with itself. The  'pivot_vector' and the 'vector' forms the 'xi' and 'xj' of the above Self Attention function.

### Demonstrating self_attention with dummy data

#### Define a custom self attention function
"""

# Custom self-attention function
def self_attention(input_sequence):
    """
    Implements a simple self-attention mechanism for an input sequence.

    Args:
        input_sequence (np.ndarray): Input is a 2D array where each row represents a token's embedding.

    Returns:
        np.ndarray: A 2D array of the same shape as the input_sequence, containing the attended representations.
    """
    # Initialize the output array with the same shape as input_sequence
    output = np.zeros(shape=input_sequence.shape)

    # Iterate over each token in the input sequence
    for i, pivot_vector in enumerate(input_sequence):
        scores = np.zeros(shape=(len(input_sequence), ))  # Initialize pairwise scores

        # Calculate pairwise similarity scores between the current token (pivot_vector) and all other tokens
        for j, vector in enumerate(input_sequence):
            scores[j] = np.dot(pivot_vector, vector.T)  # Compute dot product (similarity)

        # Scale the scores by the square root of the embedding dimension
        scores /= np.sqrt(input_sequence.shape[1])

        # Apply softmax to convert scores into probabilities
        scores = tf.nn.softmax(scores)

        # Initialize a new representation for the pivot token as a weighted sum of token embeddings
        new_pivot_representation = np.zeros(shape=pivot_vector.shape)
        for j, vector in enumerate(input_sequence):
            new_pivot_representation += vector * scores[j]  # Add weighted embedding to new representation

        # Store the new representation in the output array
        output[i] = new_pivot_representation

    return output

# Optional Homework:
# Extend the function to print the attention score matrix for better understanding and visualization.

"""#### Use a dummy data and find its vectors

The data first passes through the TextVectorization layer then through the Embedding layer and later the Self Attention scores are calculated
"""

# First, vectorize raw text using TextVectorization
dummy_vocab = ["movie was very nice", "film was good"]  # Dummy vocabulary with sample sentences
text_vec = layers.TextVectorization(
    max_tokens=5,             # Maximum vocabulary size allowed (5 unique tokens)
    output_sequence_length=3  # Each output sequence will have exactly 3 tokens
)
text_vec.adapt(dummy_vocab)    # Learn the vocabulary from the dummy sentences
print(text_vec("movie"))       # Vectorize the input text "movie"

# Q: Why the zeros? Why shape 3?
# A:
# - The output shape is (3,) because `output_sequence_length=3`, which means every tokenized sequence is padded or truncated to exactly 3 tokens.
# - Zeros are added as padding to ensure the sequence has a fixed length of 3. If the tokenized output has fewer than 3 tokens, zeros are appended.

# Q: Output type?
# A:
# - The output is a NumPy array of integers. Each integer corresponds to the index of a token in the vocabulary created during the `adapt` process.

# Then obtain embeddings from text indices using the Embedding layer
int_text = text_vec(["movie was good"])  # Convert text to integer indices using TextVectorization
print(int_text)                          # Prints the vectorized text indices

embedding = layers.Embedding(input_dim=5, output_dim=4)(int_text)  # Create embeddings for indices
print(embedding)                          # Prints the embedding representation for the indices

# Why 5?
# - The `input_dim` in the `Embedding` layer is set to 5 because it must match the size of the vocabulary.
# - During the TextVectorization process, we defined `max_tokens=5`, which limits the vocabulary to 5 unique tokens.
# - The `Embedding` layer expects the `input_dim` to match the number of unique tokens in the vocabulary (plus possibly a token for padding, depending on implementation).

# Explanation:
# 1. **Text Vectorization**:
#    - The `TextVectorization` layer maps the input sentence `"movie was good"` into integer indices based on the learned vocabulary.
#    - For example, the sentence may map to something like `[1, 2, 3]` if "movie", "was", and "good" are at indices 1, 2, and 3 in the vocabulary.

# 2. **Embedding Layer**:
#    - The `Embedding` layer maps each index (e.g., `1`, `2`, `3`) to a dense vector of size `output_dim=4`.
#    - The `output_dim` (4 in this case) determines the dimensionality of each embedding vector.
#    - For example, index `1` might be represented as `[0.25, -0.15, 0.8, 0.1]`, index `2` as `[0.4, 0.1, -0.2, 0.3]`, and so on.

# Output:
# - `int_text`: A tensor containing integer indices for the input sentence, e.g., `[[1, 2, 3]]`.
# - `embedding`: A tensor of shape `(1, 3, 4)` where:
#   - `1` is the batch size (1 sentence),
#   - `3` is the sequence length (3 tokens),
#   - `4` is the embedding dimension (`output_dim=4`).

"""#### Output from the attention function"""

# Compute output of attention module
attention_outputs = self_attention(embedding[0].numpy())
print(attention_outputs.shape)
print(attention_outputs)

"""## Attention Eqn. with Queries, Keys and Values

We computed the Self Attention based on the inputs of vectors themselves. This means that for fixed inputs, these attention weights would always be fixed. In other words, there are no learnable parameters. Need to introduce some learnable parmeters which will make the self attention mechanism more flexible and tunable for various tasks. To fullfil this purpose, three weight matices are introduced and multiplied with input $x_i$ seperately and three new terms **Queries(Q), Keys(K) and Values(V)** comes into picture as given by equations below. Vectorized implemenation  & Shape tracking are also shown along with equations.

**Vectorized implemenation  & Shape tracking**

$ d_{model} $ = Embedding vector for each word ( 512 as per the paper).

$ X   \Rightarrow (T \times d_{model}) $


$ Q = X W^{Q}   \Rightarrow (T \times d_{model}) \times (d_{model} \times d_k  )  \Rightarrow   (T \times d_{k}) $


$ K = X W^{K}   \Rightarrow (T \times d_{model}) \times (d_{model} \times d_k  )  \Rightarrow   (T \times d_{k}) $


$ V = X W^{V}   \Rightarrow (T \times d_{model}) \times (d_{model} \times d_v  )  \Rightarrow   (T \times d_{v}) $

Dot product of Queries and Keys:

$ Q K^{T}   \Rightarrow (T \times d_{k}) \times (d_{k} \times T  )  \Rightarrow   (T \times T) $

T query vectors and T key vectors (Input Sequence), so need TxT attention weights. Make Sense! Taking SoftMax doesn't change the shape.

 **Shapes as per the paper**

$
\begin{array}{|c|c|} \hline
Object   &  Shape & values  \\ \hline
q_i, k_i  &  d_k  &  (64,) \\
v_i   &   d_v   &   (64,)  \\
x_i   &   d_{model}   & (512,)  \\
W^{Q}, W^{K}  &   d_{model} \times d_k   &   (512, 64)  \\
W^{V}   &   d_{model} \times d_v   &  (512,64)  \\ \hline
\end{array}
$

**Batch consideration**

In code, a batch of N samples are processed at a time. Everyting would be  **N times**, like: $ N \times T \times d_k $ instead of just $ T \times d_k$.

**Fianl Scaled Dot Product Attention** equation inside each attention head with **Queries(Q)**, **Keys(Q)**, and **Values(V)**, which returns a Attention vector.

<center>
<img src= "https://cdn.extras.talentsprint.com/aiml/Experiment_related_data/Images/Scaled_dot_product_Attention.png" width=250px/>

</center>


$$Attention(Q, K, V) = softmax(\frac{QK^T)}{\sqrt{d_k}})V$$

## Multihead Attention

If the output of the final Encoder in the stack is passed to the Value and Key parameters in the Encoder-Decoder Attention.

The Encoder-Decoder Attention is therefore getting a representation of both the target sequence (from the Decoder Self-Attention) and a representation of the input sequence (from the Encoder stack). It, therefore, produces a representation with the attention scores for each target sequence word that captures the influence of the attention scores from the input sequence as well.

As this passes through all the Decoders in the stack, each Self-Attention and each Encoder-Decoder Attention also add their own attention scores into each word’s representation.

In the Transformer, the Attention module repeats its computations multiple times in parallel. Each of these is called an Attention Head. The Attention module splits its Query, Key, and Value parameters N-ways and passes each split independently through a separate Head. All of these similar Attention calculations are then combined together to produce a final Attention score. This is called Multi-head attention and gives the Transformer greater power to encode multiple relationships and nuances for each word.

In the paper, the diagram for a scaled dot product attention does not use any weights at all. Instead, the weights are included only in the multi head attention block, shown in figure below :
<br><br>
<center>
<img src= "https://cdn.extras.talentsprint.com/aiml/Experiment_related_data/Images/Multi_head_attention_with_weights.png" width=900px/>
</center>

### Understanding the shape
<br>
<center>
<img src= "https://cdn.extras.talentsprint.com/aiml/Experiment_related_data/Images/Multi_head_attention_shape_tracking.png" width=750px>
</center>
<br>

**Final Projection :** $ Output = concat(A_1, A_2, ..., A_h)  W^{o} $

**Shape of :**  $ concat (A_1, A_2, ..., A_h) \Rightarrow  (T \times hd_v) $

**Shape of:**  $  W^{o} \Rightarrow (hd_v \times d_{model}) $

**Shape of final:**  $ Ouput = concat (A_1, A_2, ..., A_h) W^{o} \Rightarrow  (T \times hd_v) \times (hd_v \times d_{model})  \Rightarrow  (T \times d_{model}) \Leftarrow $ **Back to the initial input shape.**

Batch size is not displayed here.

## Transformer Encoder Block

The Transformer Encoder consists of a stack of
 identical layers (Encoder Block) as shown in figure below, where each layer further consists of two main sub-layers:

* The first sub-layer comprises a multi-head attention mechanism that receives the queries, keys, and values as inputs.
* A second sub-layer comprises a fully-connected feed-forward network.

Following each of these two sub-layers is layer normalization, into which the sub-layer input (through a residual/skip connection) and output are fed.

Regularization is also introduced into the model by applying a dropout to the output of each sub-layer (before the layer normalization step), as well as to the positional encodings before these are fed into the encoder.



<br>
<center>
<img src="https://cdn.extras.talentsprint.com/aiml/Experiment_related_data//Images/Encoder_tfr_block_unfolded.png"  width=600 px />$⇒$
<img src="https://cdn.extras.talentsprint.com/aiml/Experiment_related_data/Images/Encoder_tfr_block.png" width=180 px/>

</center>

The transformer encoder architecture typically consists of multiple layers, each of which includes a self-attention mechanism and a feed-forward neural network. The self-attention mechanism allows the model to weigh the importance of different input sequence parts by calculating the embeddings' dot product. This mechanism is also known as multi-head attention.

The feed-forward network allows the model to extract higher-level features from the input. This network usually comprises two linear layers with a ReLU activation function in between. The feed-forward network allows the model to extract deeper meaning from the input data and more compactly and usefully represent the input.In the paper, an ANN with one hidden layer and a ReLu activation in the middle  with no activation function at output layer has been implemented.

The transformer encoder is a crucial part of the transformer encoder-decoder architecture, which is widely used for natural language processing tasks.

## Encoder Transformer
Stacking transormer blocks gives a Transfomer! Shown in figure below:

<br>
<center>
<img src= "https://cdn.extras.talentsprint.com/aiml/Experiment_related_data/Images/Encoder_transfomer.png" width=1000px/>
</center>

#### Define TransformerEncoder class
"""

class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim    # Dimension of the embeddings used in the Transformer. Example: 4 in the dummy case.
        self.dense_dim = dense_dim    # Number of neurons in the feedforward dense layers.
        self.num_heads = num_heads    # Number of attention heads in the MultiHeadAttention layer.
        # Define the MultiHeadAttention layer with the specified number of heads and embedding dimension.
        self.attention = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        # Define a feedforward network as a sequential model:
        # 1. First Dense layer applies a ReLU activation with `dense_dim` units.
        # 2. Second Dense layer maps back to `embed_dim` to preserve the shape for stacking encoders.
        self.dense_proj = keras.Sequential([
            layers.Dense(dense_dim, activation="relu"),
            layers.Dense(embed_dim),
        ])
        # Layer normalization to normalize intermediate representations (improves training stability).
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    # Call function based on the Transformer architecture.
    def call(self, inputs, mask=None):
        if mask is not None:
            # Expand mask dimensions to align with the shape required for attention computation.
            mask = mask[:, tf.newaxis, :]
        # Apply self-attention:
        # Inputs are used as Query, Key, and Value to compute the attention scores.
        attention_output = self.attention(query=inputs,  # Query is the input sequence.
                                          value=inputs,  # Value is also the input sequence.
                                          key=inputs,    # Key is the input sequence.
                                          attention_mask=mask)  # Optional mask for padded tokens.

        # Add residual connection: inputs + attention_output, followed by Layer Normalization.
        proj_input = self.layernorm_1(inputs + attention_output)  # Residual connection + Normalization.
        # Pass through the feedforward network (dense projection).
        proj_output = self.dense_proj(proj_input)
        # Add residual connection: proj_input + proj_output, followed by Layer Normalization.
        return self.layernorm_2(proj_input + proj_output)  # Final output of the encoder block.

    def get_config(self):
        # Define configuration settings for serialization and deserialization.
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,  # Embedding dimension configuration.
            "num_heads": self.num_heads,  # Number of attention heads configuration.
            "dense_dim": self.dense_dim,  # Dense layer dimension configuration.
        })
        return config

"""#### Model definition"""

# Build the Transformer encoder
vocab_size = 20000  # Vocabulary size for the input text
embed_dim = 256      # Dimension of the embeddings used in the Transformer encoder
num_heads = 2        # Number of attention heads in the MultiHeadAttention layer
dense_dim = 32       # Number of neurons in the feedforward dense layers

# Define the input layer: input text as string.
inputs = keras.Input(shape=(1,), dtype=tf.string)

# Apply TextVectorization layer to convert raw text into integer sequences.
x = text_vectorization(inputs)

# Apply Embedding layer to transform integer indices into dense vector representations.
x = layers.Embedding(vocab_size, embed_dim)(x)

# Pass through the custom TransformerEncoder block.
x = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)

# Apply GlobalMaxPooling1D to reduce the output sequence to a single vector (max pooling over time dimension).
x = layers.GlobalMaxPooling1D()(x)

# Apply Dropout to reduce overfitting during training.
x = layers.Dropout(0.5)(x)

# Final Dense layer for binary classification with sigmoid activation.
outputs = layers.Dense(1, activation="sigmoid")(x)

# Define the model using the inputs and outputs.
model = keras.Model(inputs, outputs)

# Compile the model with RMSProp optimizer, binary crossentropy loss, and accuracy as the evaluation metric.
model.compile(optimizer="rmsprop",
              loss="binary_crossentropy",
              metrics=["accuracy"])

# Print the summary of the model architecture.
model.summary()

"""#### Train and evaluate the performance of the model *(Switch to GPU runtime if needed)*"""

# Fit the model on train set
callbacks = [keras.callbacks.ModelCheckpoint("transformer_encoder.keras", save_best_only=True)]

# Change target shape from (None,) to (None, 1)
train_dataset = train_ds.map(lambda x, y: (x, tf.reshape(y, (-1,1))))
val_dataset = val_ds.map(lambda x, y: (x, tf.reshape(y, (-1,1))))

model.fit(train_dataset,
          validation_data = val_dataset,
          epochs = 10,
          callbacks = callbacks)

# Load the trained Transformer model from the specified file
model = keras.models.load_model(
    "transformer_encoder.keras",  # Path to the saved model file
    custom_objects={"TransformerEncoder": TransformerEncoder}  # Custom class definition for TransformerEncoder layer
)

# Evaluate the model on the test dataset and print the test accuracy
print(f"Test acc: {model.evaluate(test_ds)[1]:.3f}")

"""#### Prediction"""

txt = "It was a great movie"  # Define a simple string
myTensor = tf.convert_to_tensor(txt, dtype=tf.string)  # Convert the string into a TensorFlow tensor of type string
print(myTensor)  # Print the tensor

pred = model(tf.reshape(myTensor, (-1, 1)))  # Reshape the tensor and pass it through the model
pred  # Print the prediction result

label_index = int(pred.numpy()[0, 0] + 0.5)  # Convert prediction to integer label (0 or 1)
label_index  # This will give the predicted label based on the rounded output

mapping = {0: 'Negative', 1: 'Positive'}  # Mapping from label index to sentiment category
label = mapping[label_index]  # Convert numerical label to corresponding sentiment label
label  # This will return the sentiment label, either 'Negative' or 'Positive'

def make_prediction(input_text, tf_model):
    # Convert the input_text to a tensor of type string
    myTensor = tf.convert_to_tensor(input_text, dtype=tf.string)

    # Make a prediction using the TensorFlow model, reshaping input to match expected dimensions
    pred = tf_model(tf.reshape(myTensor, (-1, 1)))

    # Convert the predicted value to an integer label (rounding the value and converting it to index 0 or 1)
    label_index = int(pred.numpy()[0, 0] + 0.5)

    # Mapping the label index (0 or 1) to the corresponding sentiment ('Negative' or 'Positive')
    mapping = {0: 'Negative', 1: 'Positive'}

    # Get the sentiment label from the mapping
    label = mapping[label_index]

    # Return the label
    return label

make_prediction("It was a great movie", model)

make_prediction("It was a bad movie", model)

"""## Positional Embedding

**Positional Embedding = Word Embedding + Positional Encoding**

**Positional Encoding**

Passing embeddings directly into the transformer block results in missing of information about the order of tokens. As attention is permutation invariant i.e. order of token does not matter to attention.
Although transformers are a sequence model, it appears that this important detail has somehow been lost. Positional encoding is for rescue.

Positional encoding add positional information to the existing embeddings.

**A unique set of numbers added at each position of the existing embeddings**, such that this new set of numbers can uniquely identify which postion they are located at.


1. Positional Encoding by SubClassing the Keras Embedding Layer (Trainable)
2. Positional Encoding scheme as per the paper (Non-Trainable)

 In this scheme the encoding is created by using a set of sins and cosines at different frequencies. The  paper uses the following formula for calculating the positional encoding. [Positional Encoding Vizualization.](https://erdem.pl/2021/05/understanding-positional-encoding-in-transformers)

$$\Large{PE_{(pos, 2i)} = \sin(pos / 10000^{2i / d_{model}})} $$
$$\Large{PE_{(pos, 2i+1)} = \cos(pos / 10000^{2i / d_{model}})} $$

We are going to implement Positional Encoding by SubClassing the Keras Embedding Layer (Trainable). Thus Instead of using the Embedding layer from keras define a PositionalEmbedding class and create a new model using it as the embedding layer.
"""

# Using positional encoding to re-inject order information

class PositionalEmbedding(layers.Layer):
    def __init__(self, sequence_length, input_dim, output_dim, **kwargs):  # input_dim = (token) vocabulary size, output_dim = embedding size
        super().__init__(**kwargs)
        # Embedding layer for tokens (words)
        self.token_embeddings = layers.Embedding(input_dim=input_dim, output_dim=output_dim)  # Q: what is input_dim and output_dim? A: vocab size, embedding dim

        # Embedding layer for positions, representing the positions in the sequence
        self.position_embeddings = layers.Embedding(input_dim=sequence_length, output_dim=output_dim)  # Q: Why input_dim = seq_length? A: there are seq_len; no. of possible positions

        # Store inputs for later use
        self.sequence_length = sequence_length
        self.input_dim = input_dim
        self.output_dim = output_dim

    # Define the forward pass of the layer
    def call(self, inputs):  # inputs will be a batch of sequences (batch, seq_len)
        length = tf.shape(inputs)[-1]  # Get the sequence length from the input
        positions = tf.range(start=0, limit=length, delta=1)  # Generate position indices for each token in the sequence
        embedded_tokens = tf.reshape(self.token_embeddings(inputs), (-1, length, self.output_dim))  # Embed tokens into dense vectors
        embedded_positions = tf.reshape(self.position_embeddings(positions), (-1, length, self.output_dim))  # Embed position indices into dense vectors

        # Add the token embeddings and position embeddings to re-inject order information
        return layers.Add()([embedded_tokens, embedded_positions])  # ADD the embeddings

    # Compute the mask to avoid attending to padding tokens (masking zeros)
    def compute_mask(self, inputs, mask=None):  # makes this layer a mask-generating layer
        if mask is None:
            return None
        return tf.math.not_equal(inputs, 0)  # Return True for non-zero tokens (i.e., valid tokens)

    # This method is used to reinstantiate the layer during model saving and loading
    def get_config(self):
        config = super().get_config()
        config.update({
            "output_dim": self.output_dim,
            "sequence_length": self.sequence_length,
            "input_dim": self.input_dim,
        })
        return config

# What does tf.math.not_equal() do?

a = tf.constant([1,0,2,0,3])  # 'a' is a TensorFlow tensor containing the values [1, 0, 2, 0, 3]
print(a)  # This will print the tensor 'a': [1, 0, 2, 0, 3]

# tf.math.not_equal() compares each element in tensor 'a' to 0 and returns a boolean tensor
# True for elements that are not equal to 0, and False for elements that are equal to 0.
print(tf.math.not_equal(a, 0))  # This will output: [True, False, True, False, True]
# Explanation of the result:
# - 1 is not equal to 0, so it returns True
# - 0 is equal to 0, so it returns False
# - 2 is not equal to 0, so it returns True
# - 0 is equal to 0, so it returns False
# - 3 is not equal to 0, so it returns True

"""#### Model Definition"""

# Combining the Transformer encoder with positional embedding

# Set hyperparameters
vocab_size = 20000           # Vocabulary size, which determines the size of the token embedding
sequence_length = 600        # Maximum sequence length (i.e., the number of tokens in each input sequence)
embed_dim = 256              # Dimensionality of the token embeddings
num_heads = 2                # Number of attention heads for the multi-head attention mechanism
dense_dim = 32               # Number of neurons in the dense layer (hidden layer size)

# Define the input layer
inputs = keras.Input(shape=(1,), dtype=tf.string)  # Input is a string, representing a sequence of text

# Apply text vectorization to convert the raw text into integer indices corresponding to the vocabulary
x = text_vectorization(inputs)  # Text Vectorization layer

# Apply positional embedding to inject order information into the token embeddings
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(x)  # Combines token embedding + positional encoding

# Apply the Transformer Encoder block to process the embedded tokens
x = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)  # Transformer Encoder block

# Apply GlobalMaxPooling to reduce the dimensionality of the sequence output
x = layers.GlobalMaxPooling1D()(x)

# Add dropout for regularization to avoid overfitting
x = layers.Dropout(0.5)(x)  # Dropout layer with a rate of 50%

# Apply a Dense layer to output a binary classification result (0 or 1)
outputs = layers.Dense(1, activation="sigmoid")(x)  # Dense layer for classification (sigmoid for binary output)

# Create the final model
model = keras.Model(inputs, outputs)

# Compile the model with the chosen optimizer, loss function, and evaluation metric
model.compile(optimizer="rmsprop",  # Optimizer
              loss="binary_crossentropy",  # Loss function for binary classification
              metrics=["accuracy"])  # Metric to evaluate model performance

# Display the summary of the model architecture
model.summary()  # Prints out the architecture of the model

"""#### Train and evaluate the model *(Switch to GPU runtime if needed)*"""

# Fit the model on train set
callbacks = [keras.callbacks.ModelCheckpoint("full_transformer_encoder.keras", save_best_only=True)]

# Change target shape from (None,) to (None, 1)
train_dataset = train_ds.map(lambda x, y: (x, tf.reshape(y, (-1,1))))
val_dataset = val_ds.map(lambda x, y: (x, tf.reshape(y, (-1,1))))

model.fit(train_dataset,
          validation_data = val_dataset,
          epochs = 10,
          callbacks = callbacks)

model = keras.models.load_model(
    "full_transformer_encoder.keras",
    custom_objects={"TransformerEncoder": TransformerEncoder,
                    "PositionalEmbedding": PositionalEmbedding})

print(f"Test acc: {model.evaluate(test_ds)[1]:.3f}")

"""#### Prediction"""

make_prediction("It was a great movie", model)

make_prediction("It was a bad movie", model)

"""## References

If you are very interested or plan to work closely on Transformers, then following are good resource that explains in simplified manner.

1. [Attention Is All You Need](https://arxiv.org/pdf/1706.03762v6.pdf)

2. [Understanding Positional  Encoding](https://erdem.pl/2021/05/understanding-positional-encoding-in-transformers)

2. [Implement Multi-Head Attention](https://machinelearningmastery.com/how-to-implement-multi-head-attention-from-scratch-in-tensorflow-and-keras)

3. [Implementing the Transformer Encoder](https://machinelearningmastery.com/implementing-the-transformer-encoder-from-scratch-in-tensorflow-and-keras/)

4. [Illustrated-transformer](https://jalammar.github.io/illustrated-transformer/)

### Please answer the questions below to complete the experiment:
"""

#@title Which layer in the Transformer model is responsible for capturing local dependencies within an input sequence? { run: "auto", form-width: "500px", display-mode: "form" }
Answer = "" #@param ["", "Self-Attention Layer", "Feedforward Neural Network Layer", "Positional Encoding Layer", "Layer Normalization"]

#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]

#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "" #@param {type:"string"}

#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "" #@param ["","Yes", "No"]

#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")