# -*- coding: utf-8 -*-
"""M4_AST_02_PEFT_C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWBTPNWdLJ08Z_vU4zO1Qz1yh81aHSLI

# Advanced Certification Programme in AI and MLOps
## A Program by IISc and TalentSprint
### Assignment 2: PEFT (Parameter Efficient Fine-Tuning)

## Learning Objectives

At the end of the experiment, you will be able to:

* understand the working of a parameter efficient finetuning method - LoRA
* load and quantize `google/gemma-2b` model
* fine-tune `google/gemma-2b` model, on the subset of `databricks-dolly-15k` dataset for text generation using LoRA
* perform inference with the  fine-tuned model

## Dataset Description

Here, in this experiment we will use **`ai-bites/databricks-mini`** dataset which is a subset of the `databricks-dolly-15k`.

The complete **`databricks-dolly-15k`** dataset is a corpus of more than 15,000 records generated by thousands of Databricks employees to enable large language models to exhibit the magical interactivity of ChatGPT. Databricks employees were invited to create **prompt / response pairs** in several different instruction categories such as

- brainstorming
- classification
- closed QA
- generation
- information extraction
- open QA
- summarization
- general QA

The contributors were instructed to avoid using information from any source on the web with the exception of Wikipedia (for particular subsets of instruction categories), and explicitly instructed to avoid using generative AI in formulating instructions or responses. Examples of each behavior were provided to motivate the types of questions and instructions appropriate to each category.

Data Splits:
- train: 15,011

Data Fields:

- ***instruction***: instruction or prompt
- ***context***: context information to consider while giving response
- ***response***: response of prompt
- ***category***: category in which instruction lies

<br>

**Example 1:**

\{
> '**instruction**': "When did Virgin Australia start operating?",
>
>'**context**': "Virgin Australia, the trading name of Virgin Australia Airlines Pty Ltd, is an Australian-based airline. It is the largest airline by fleet size to use the Virgin brand. It commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route. It suddenly found itself as a major airline in Australia's domestic market after the collapse of Ansett Australia in September 2001. The airline has since grown to directly serve 32 cities in Australia, from hubs in Brisbane, Melbourne and Sydney.",
>
>'**response**': "Virgin Australia commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route."
>
>'**category**': "closed_qa"

\}

**Example 2:**

\{
> '**instruction**': "Which is a species of fish? Tope or Rope",
>
>'**context**': " ",
>
>'**response**': "Tope"
>
>'**category**': "classification"

\}

To know more about `databricks-dolly-15k` dataset, refer [here](https://huggingface.co/datasets/databricks/databricks-dolly-15k).

Here, in this experiment we will use **`ai-bites/databricks-mini`** dataset which is a subset of the `databricks-dolly-15k`.

This subset has only those records which doesn't have a *context*. Also, *instruction* and *response* were combined in one text sentence.

Data Splits:
- train: 10,544

Data Fields:

- ***text***: instruction and response combined in one text sentence

<br>

**Example 1:**

\{
> '**text**': "Instruction:\nWhich is a species of fish? Tope or Rope\n\nResponse:\nTope",

\}

**Example 2:**

\{
> '**text**': "Instruction:\nWhy can camels survive for long without water?\n\nResponse:\nCamels use the fat in their humps to keep them filled with energy and hydration for long periods of time.",

\}

**Example 3:**

\{
> '**text**': "Instruction:\nAlice's parents have three daughters: Amy, Jessy, and what's the name of the third daughter?\n\nResponse:\nThe name of the third daughter is Alice",

\}

To know more about `ai-bites/databricks-mini` dataset, refer [here](https://huggingface.co/datasets/ai-bites/databricks-mini).

## Information

### **Parameter-Efficient Fine-Tuning (PEFT) methods**

Fine-tuning large pretrained models is often prohibitively costly due to their scale. Parameter-Efficient Fine-Tuning (PEFT) methods enable efficient adaptation of large pretrained models to various downstream applications by only fine-tuning a small number of (extra) model parameters instead of all the model's parameters. This significantly decreases the computational and storage costs. Recent state-of-the-art PEFT techniques achieve performance comparable to fully fine-tuned models.

PEFT is integrated with Transformers for easy model training and inference, and Accelerate for distributed training and inference for really big models.

[PEFT](https://github.com/huggingface/peft) is also a new open-source library from Hugging Face to enable efficient adaptation of pre-trained language models (PLMs) to various downstream applications ***without*** fine-tuning all the model's parameters.

PEFT currently includes techniques for:

- **LoRA:** Low-Rank Adaptation of Large Language Models
- **Prefix Tuning:** P-Tuning v2
- **P-Tuning**
- **Prompt Tuning**

### **LoRA**

It is a technique that accelerates the fine-tuning of large models while consuming less memory.

To make fine-tuning more efficient, LoRA's approach is to represent the weight updates with two smaller matrices (called update matrices) through low-rank decomposition.

A and B are update matrices in below figure.

<center>
<img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/peft/lora_diagram.png" width=900px>
</center>
<br>

- These new matrices can be trained to **adapt to the new data** while keeping the overall number of changes low.
- The original weight matrix **remains frozen** and doesn't receive any further adjustments.
- To produce the final results, both the original and the adapted weights are **combined**.

### Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# 
# # For loading models, tokenizers, and datasets from HuggingFace
# !pip install -q accelerate==0.27.1
# !pip install -q datasets==2.17.0
# !pip install -q transformers==4.38.0
# 
# # For doing PEFT
# !pip install -q peft==0.8.2
# !pip install -q trl==0.7.10    # TRL - Transformer Reinforcement Learning; built on top of the 'transformers' library; a
#                                #       Full stack library to fine-tune and align large language models

# Install bitsandbytes for quantization
!pip -q uninstall -y bitsandbytes
!pip -q install bitsandbytes

import os
os.environ["LD_LIBRARY_PATH"] += ":/usr/local/lib/python3.11/dist-packages/bitsandbytes/lib"
# The above line ensures that when the Python process looks for shared libraries, it will also search in the /usr/local/lib/python3.11/dist-packages/bitsandbytes/lib directory,
# which may contain necessary shared libraries for the bitsandbytes package.

"""### Setup Steps:"""

#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "" #@param {type:"string"}

#@title Please enter your password (your registered phone number) to continue: { run: "auto", display-mode: "form" }
password = "" #@param {type:"string"}

#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "M4_AST_02_PEFT_C" #name of the notebook

def setup():
#  ipython.magic("sx pip3 install torch")

    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getAnswer() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "answer" : Answer, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://aimlops-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None


# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None

def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None


def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer():
  try:
    if not Answer:
      raise NameError
    else:
      return Answer
  except NameError:
    print ("Please answer Question")
    return None


def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()
else:
  print ("Please complete Id and Password cells before running setup")

"""### Import required packages"""

import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import TrainingArguments
from trl import SFTTrainer             # Supervised Fine-tuning (SFT) Trainer

import warnings
warnings.filterwarnings('ignore')

"""### Login to HuggingFace"""

# Run, and paste your HF Access token when prompted
!huggingface-cli login

# OR

# from huggingface_hub import notebook_login
# notebook_login()            ## paste your HF Access token when prompted

"""### **Load Model & Tokenizer**

* Load the model - `"google/gemma-2b"`

  <font color="#990000">NOTE that you will be required to raise a request before using the "google/gemma-2b" model.</font>

  <font color="#990000">You can login to your account on HuggingFace and then go to https://huggingface.co/google/gemma-2b, click on "Accept License" and follow the prompts. Requests are approved instantly.</font>

* Load the tokenizer
* Visualize the model architecture
* Finally, query the model with a prompt and see the response before fine-tuning
"""

# Load model from HF Model Hub

"""
Gemma-2b model has 2 billion parameters.
Look into Model card: https://huggingface.co/google/gemma-2b
"""



model_name = "google/gemma-2b"          # username/repo-name

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load model
model = AutoModelForCausalLM.from_pretrained(model_name,                # Make sure you have the access to this model
                                             device_map='auto'          # to load the entire model on the GPU if its available
                                             )

# Visualize the model architecture
print(model)

# Check the device of the model
device = next(model.parameters()).device
device

# Query the model with a prompt and see the response before fine-tuning

input_text = "What should I do on a trip to Europe?"

input_ids = tokenizer(input_text, return_tensors="pt").to(device)
outputs = model.generate(**input_ids, max_length=128)

print(tokenizer.decode(outputs[0]))

# Query the model with a prompt and see the response before fine-tuning

input_text = "Explain the process of photosynthesis in a way that a child could understand"

input_ids = tokenizer(input_text, return_tensors="pt").to(device)
print(input_ids)

outputs = model.generate(**input_ids, max_length=128)
print(tokenizer.decode(outputs[0]))

"""## Motivation for PEFT

- Try to finetune Gemma-2b on the subset of `databricks-dolly-15k` dataset **without LoRA**
  * Load and visualize the dataset
  * Initiate the trainer
  * Start the training
  * Note that its impossible to fine-tune on a single 14GB GPU (T4) on colab
"""

# Load dataset
dataset = load_dataset("ai-bites/databricks-mini", split="train[0:1000]")
dataset

print(dataset['text'][0])

print(dataset['text'][1])

# Set training parameters

training_arguments = TrainingArguments(
    output_dir="./results_1",                   # Output directory where the model predictions and checkpoints will be stored
    num_train_epochs=2,                         # Number of training epochs
    per_device_train_batch_size=4,              # Batch size per GPU for training
    gradient_accumulation_steps=4,              # Batch size per GPU for evaluation
    optim="paged_adamw_32bit",                  # Optimizer to use (AdamW optimizer)
    save_steps=25,                              # Save checkpoint every X updates steps
    logging_steps=25,                           # Log every X updates steps
    learning_rate=2e-4,                         # Initial learning rate (AdamW optimizer)
    weight_decay=0.001,                         # Weight decay to apply to all layers except bias/LayerNorm weights
    max_grad_norm=0.3,                          # Maximum gradient normal (gradient clipping)
    warmup_ratio=0.03,                          # Ratio of steps for a linear warmup (from 0 to learning rate)
    group_by_length=True,                       # Group sequences into batches with same length; Saves memory and speeds up training considerably
    lr_scheduler_type="constant",               # Learning rate schedule (constant a bit better than cosine)
    report_to="none",                           # Disable logging to W&B (Weights and Biases)
)

# Fine-tune the model

from trl import SFTTrainer         # Supervised Fine-tuning step (SFT) Trainer

trainer = SFTTrainer(model=model,
                     train_dataset=dataset,
                     tokenizer=tokenizer,
                     dataset_text_field="text",
                     args=training_arguments
                     )

print("Initialized trainer for training!")

trainer.train()

"""<font color="#119911">Since it is difficult to fine-tune such a large model having 2 billion parameters, the above code cell will run out of memory. It will give `OutOfMemoryError` and the session will be crashed.</font>

At this point, you can restart the session and continue executing the below code cells from here. Make sure you are on GPU runtime.

### <font color="#990000">Restart Session/Runtime</font>

# Finetune using Parameter Efficient Fine-tuning (PEFT)

### Import required packages
"""

import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import BitsAndBytesConfig
from transformers import TrainingArguments
from peft import LoraConfig, PeftModel
from trl import SFTTrainer

import warnings
warnings.filterwarnings('ignore')

"""### Load dataset"""

# Load dataset
dataset = load_dataset("ai-bites/databricks-mini", split="train[0:1000]")
dataset

print(dataset['text'][0])

print(dataset['text'][1])

"""## Load and Quantize the Model

**Quantization** is a technique to reduce the size of deep neural networks (including LLMs) by changing the precision of the weights and biases data structure.

Quantization techniques reduce memory and computational costs by representing weights and activations with lower-precision data types like 8-bit integers (int8).

**bitsandbytes** is the easiest option for quantizing a model to 8-bit and 4-bit.

* 8-bit quantization multiplies outliers in fp16 with non-outliers in int8, converts the non-outlier values back to fp16, and then adds them together to return the weights in fp16. This reduces the degradative effect outlier values have on a model's performance.

* 4-bit quantization compresses a model even further, and it is commonly used with [QLoRA](https://hf.co/papers/2305.14314) to finetune quantized LLMs.

You can quantize a model by passing a `BitsAndBytesConfig` to `from_pretrained()` method.

To know more about bitsandbytes, refer [here](https://huggingface.co/docs/transformers/main/en/quantization/bitsandbytes?bnb=4-bit).
"""

# Create `BitsAndBytesConfig` object for Quantization

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,                            # Activate 4-bit precision base model loading
    bnb_4bit_quant_type="nf4",                    # Quantization type (fp4 or nf4)    nf4 -> Normal Float 4
    bnb_4bit_compute_dtype=torch.float16,         # Compute dtype for 4-bit base models
    bnb_4bit_use_double_quant=False,              # Whether to activate nested quantization for 4-bit base models (double quantization)
)

model_name = "google/gemma-2b"

# Load and quantize the base model
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=quantization_config,    # note that GPU is needed for quantization
                                             device_map="auto"                           # to load the entire model on the GPU if its available
                                             )
model.config.use_cache = False
model.config.pretraining_tp = 1

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

"""### **Fine-tuning Model using LoRA**

To fine-tune a model using LoRA, you need to:

- Instantiate a base model, here it is `google/gemma-2b`
- Create a configuration (`LoraConfig`) where you define LoRA-specific parameters
- Pass this configuration to SFTTrainer class `peft_config = LoraConfig(...)`
- Start the training process
"""

# Create LoRA configuration object with LoRA-specific parameters

peft_config = LoraConfig(
    lora_alpha=16,                         # LoRA scaling factor
    r=4,                      # 8, 16, 32  # LoRA attention dimension; the rank of the update matrices
    lora_dropout=0.1,                      # Dropout probability for LoRA layers
    bias="none",                           # specifies if the bias parameters should be trained
    task_type="CAUSAL_LM",                 # telling lora that this is a causal language modeling task
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj","gate_proj", "up_proj"]            # layers/blocks present in gemma-2b model
)

from peft import get_peft_model

# Number of trainable parameters
get_peft_model(model, peft_config=peft_config).print_trainable_parameters()

"""From above we can see that now only 14.25% out of 2 billion parameters will be updated during the training process."""

# Set training parameters

training_arguments = TrainingArguments(
    output_dir="./results",                     # Output directory where the model predictions and checkpoints will be stored
    num_train_epochs=2,                         # Number of training epochs
    per_device_train_batch_size=4,              # Batch size per GPU for training
    gradient_accumulation_steps=4,              # Batch size per GPU for evaluation
    optim="paged_adamw_32bit",                  # Optimizer to use (AdamW optimizer)
    save_steps=25,                              # Save checkpoint every X updates steps
    logging_steps=25,                           # Log every X updates steps
    learning_rate=2e-4,                         # Initial learning rate (AdamW optimizer)
    weight_decay=0.001,                         # Weight decay to apply to all layers except bias/LayerNorm weights
    max_grad_norm=0.3,                          # Maximum gradient normal (gradient clipping)
    warmup_ratio=0.03,                          # Ratio of steps for a linear warmup (from 0 to learning rate)
    group_by_length=True,                       # Group sequences into batches with same length; Saves memory and speeds up training considerably
    lr_scheduler_type="constant",               # Learning rate schedule (constant a bit better than cosine)
    report_to="none",                           # Disable logging to W&B (Weights and Biases)
)

# Set Supervised Fine-Tuning (SFT) parameters

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,                  # LoRA configuration to use
    dataset_text_field="text",
    max_seq_length=40,                        # Maximum sequence length to use
    tokenizer=tokenizer,
    args=training_arguments,
    packing=True,                             # Pack multiple short examples in the same input sequence to increase efficiency
)

# Train model
trainer.train()

# Save model
new_model = "gemma-finetuned"
trainer.model.save_pretrained(new_model)

"""## Prompt the newly fine-tuned model
* Load and MERGE the LoRA weights with the model weights
* Run inference with the same prompt we used to test the pre-trained model
"""

# Base model
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map="auto",
)

# Load and MERGE the LoRA weights with the model weights

model = PeftModel.from_pretrained(base_model, new_model)
model = model.merge_and_unload()

model

# Reload tokenizer to save it
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Run inference

input_text = "What should I do on a trip to Europe?"

input_ids = tokenizer(input_text, return_tensors="pt").to("cuda")
print(input_ids)
outputs = model.generate(**input_ids, max_length=128)
print(tokenizer.decode(outputs[0]))

tokenizer.decode(outputs[0])

# Run inference

input_text = "What are some good places to visit during holidays?"

input_ids = tokenizer(input_text, return_tensors="pt").to("cuda")
print(input_ids)
outputs = model.generate(**input_ids, max_length=128)
print(tokenizer.decode(outputs[0]))

"""### Please answer the questions below to complete the experiment:



"""

#@title Select the False statement w.r.t LoRA: { run: "auto", form-width: "500px", display-mode: "form" }
Answer = "" #@param ["", "It is a technique that accelerates the fine-tuning of large models while consuming less memory", "During training, the original weight matrix remains frozen and doesn't receive any further adjustments", "During inference, only the original weight matrix is used to produce final results", "None of the above"]

#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]

#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "" #@param {type:"string"}

#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "" #@param ["","Yes", "No"]

#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]

#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")