# -*- coding: utf-8 -*-
"""M4_SNB_MiniProject_1_PartB_Deploy_Medical_Q&A_GPT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHXr1JX6EXVVmxeCRWh16dOTaWoSMikv

# Advanced Certification Programme in AI and MLOps
## A programme by IISc and TalentSprint
### Mini-Project: Medical Q&A using GPT2 | Deployment on Spaces

**DISCLAIMER:** THIS NOTEBOOK IS PROVIDED ONLY AS A REFERENCE SOLUTION NOTEBOOK FOR THE MINI-PROJECT. THERE MAY BE OTHER POSSIBLE APPROACHES/METHODS TO ACHIEVE THE SAME RESULTS.

## Learning Objectives

At the end of the experiment, you will be able to:

* perform data preprocessing, EDA and feature extraction on the Medical Q&A dataset
* load a pre-trained tokenizer
* finetune a GPT-2 language model for medical question-answering
* upload your fine-tuned model to Hugging Face Model Hub
* deploy application with uploaded model on HuggingFace Spaces using Gradio

## Dataset Description

The dataset used in this project is the *Medical Question Answering Dataset* ([MedQuAD](https://github.com/abachaa/MedQuAD/tree/master)). It includes medical question-answer pairs along with additional information, such as the question type, the question *focus*, its UMLS(Unified Medical Language System) details like - Concept Unique Identifier(*CUI*) and Semantic *Type* and *Group*.

To know more about this data's collection, and construction method, refer to this [paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-3119-4).

The data is extracted and is in CSV format with below features:

- **Focus**: the question focus
- **CUI**: concept unique identifier
- **SemanticType**
- **SemanticGroup**
- **Question**
- **Answer**

## Grading = 10 Points

## Information

Healthcare professionals often have to refer to medical literature and documents while seeking answers to medical queries. Medical databases or search engines are powerful resources of upto date medical knowledge. However, the existing documentation is large and makes it difficult for professionals to retrieve answers quickly in a clinical setting. The problem with search engines and informative retrieval engines is that these systems return a list of documents rather than answers. Instead, healthcare professionals can use question answering systems to retrieve short sentences or paragraphs in response to medical queries. Such systems have the biggest advantage of generating answers and providing hints in a few seconds.

### Problem Statement

Fine-tune gpt2 model on medical-question-answering-dataset for performing response generation for medical queries. Later, deploy the fine-tuned model on Hugging Face Spaces.

Please refer to ***M6 Assignment-1 Fine-tune GPT2*** and ***M6 AdditionalNB Fine-tune GPT2 for TextClassification*** to get familiar with how to load pre-trained gpt2 tokenizer and model.

Please refer to ***The demo session held on 14 Sep - Hugging Face Spaces Deployment*** to get familiar with how to do deployment using Hugging Face Spaces.

### Installing Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q uninstall pyarrow -y
# !pip -q install pyarrow==15.0.2
# !pip -q install datasets
# !pip -q install accelerate
# !pip -q install transformers

"""### <font color="#990000">Restart Session/Runtime</font>

### Import required packages
"""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import torch
from transformers import GPT2Tokenizer, GPT2LMHeadModel, DataCollatorForLanguageModeling
from transformers import Trainer, TrainingArguments

import warnings
warnings.filterwarnings('ignore')

#@title Download the dataset
!wget -q https://cdn.iisc.talentsprint.com/AIandMLOps/MiniProjects/Datasets/MedQuAD.csv
!ls | grep ".csv"

"""**Exercise 1: Read the MedQuAD.csv dataset**

**Hint:** pd.read_csv()
"""

df = pd.read_csv("MedQuAD.csv")
df.shape

df.head()

"""### Pre-processing and EDA

**Exercise 2: Perform below operations on the dataset**

- Handle missing values
- Remove duplicates from data considering `Question` and `Answer` columns

- **Handle missing values**
"""

df.isna().sum()

# Drop missing values
df = df.dropna()
df.shape

"""- **Remove duplicates from data considering `Question` and `Answer` columns**"""

# Check duplicates
df.duplicated(subset=['Question', 'Answer']).sum()

# Drop duplicates
df = df.drop_duplicates(subset=['Question', 'Answer'])

# Check duplicates
df.duplicated(subset=['Question', 'Answer']).sum()

"""**Exercise 3: Display the category name, and the number of records belonging to top 100 categories of `Focus` column**"""

# Total categories in Focus column
print(df['Focus'].nunique())

# Displaying the distinct categories of Focus column and the number of records belonging to each category
# (Top 100 only)

print(df['Focus'].value_counts()[:100])

# Top 100 Focus categories names

top_100_focuses = df['Focus'].value_counts()[:100].index
top_100_focuses

"""### Create Training and Validation set

**Exercise 4: Create training and validation set**

- Consider 4 samples per `Focus` category, for each top 100 categories, from the dataset (It will give 400 samples for training)

- Consider 1 sample per `Focus` category (different from training set), for each top 100 categories, from the dataset (It will give 100 samples for validation)
"""

train_ques = []
train_ans = []
val_ques = []
val_ans = []

for i in top_100_focuses:
    tmp = df[df['Focus'] == i]
    train_ques.extend(tmp['Question'].values[:4].tolist())
    train_ans.extend(tmp['Answer'].values[:4].tolist())
    val_ques.extend(tmp['Question'].values[4:5].tolist())
    val_ans.extend(tmp['Answer'].values[4:5].tolist())

len(train_ques), len(train_ans), len(val_ques), len(val_ans)

"""### Pre-process `Question` and `Answer` text

**Exercise 5: Perform below tasks:**

- Combine `Question` and `Answer` for train and validation data as shown below:
    - sequence = *'\<question\>' + question-text + '\<answer\>' + answer-text + '\<end\>'*

- Join the combined text using '\n' into a single string for training and validation separately

- Save the training and validation strings as separate text files

- **Combine Question and Answer for train and val data**
"""

# Combine Questions and Answers for train and val data
## sequence = '<question>' + question + '<answer>' + answer

train_data = []
val_data = []

for i in range(len(train_ques)):
    train_data.append('<question> ' + train_ques[i] + ' <answer> ' + train_ans[i] + ' <end>')

for i in range(len(val_ques)):
    val_data.append('<question> ' + val_ques[i] + ' <answer> ' + val_ans[i] + ' <end>')

len(train_data), len(val_data)

train_data[0]

val_data[0]

"""- **Join the combined text using '\n' into a single string for training and validation separately**"""

# Train and Validation text for all Q&As

train_text = '\n'.join(list(train_data))

val_text = '\n'.join(list(val_data))

"""- **Save the training and validation strings as text files**"""

# Save the training and validation data as text files

with open("train.txt", "w") as f:
    f.write(train_text)

with open("val.txt", "w") as f:
    f.write(val_text)

"""**Exercise 6: Load pre-trained GPT2Tokenizer**

- Use checkpoint = "gpt2"
"""

# Set up the tokenizer
checkpoint = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(checkpoint)    # also try gpt2, gpt2-large and gpt2-medium, also gpt2-xl

"""**Exercise 7: Tokenize train and validation data**

- Use the loaded pre-trained tokenizer
- Use training and validation data saved in text files
"""

#from transformers import AutoTokenizer
from datasets import load_dataset

train_file_path = 'train.txt'
val_file_path = 'val.txt'

dataset = load_dataset("text", data_files={"train": train_file_path,
                                           "validation": val_file_path})

dataset

dataset['train']['text'][0]

block_size = 256     # max tokens in an input sample

def tokenize_function(examples):
    return tokenizer(examples["text"], padding='max_length', truncation=True, max_length=block_size, return_tensors='pt')

tokenized_datasets = dataset.map(tokenize_function, batched=True)  #, batch_size=128)

tokenized_datasets

len(tokenized_datasets['train']['input_ids'][0])

"""**Exercise 8: Create a DataCollator object**"""

# Create a Data collator object
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False, return_tensors="pt")

"""**Exercise 9: Load pre-trained GPT2LMHeadModel**"""

# Set up the model
model = GPT2LMHeadModel.from_pretrained(checkpoint)    # also try gpt2, gpt2-large and gpt2-medium, also gpt2-xl

"""**Exercise 10: Fine-tune GPT2 Model**

- Specify training arguments and create a TrainingArguments object (Use 30 epochs)

- Train a GPT-2 model using the provided training arguments

- Save the resulting trained model and tokenizer to a specified output directory
"""

# Set up the training arguments

model_output_path = "/content/gpt_model"

training_args = TrainingArguments(
    output_dir = model_output_path,
    overwrite_output_dir = True,
    per_device_train_batch_size = 4,
    per_device_eval_batch_size = 4,
    num_train_epochs = 30,
    save_steps = 1_000,
    save_total_limit = 2,
    logging_dir = './logs',
    )

# Train the model
trainer = Trainer(
    model = model,
    args = training_args,
    data_collator = data_collator,
    train_dataset = tokenized_datasets["train"],
    eval_dataset = tokenized_datasets["validation"],
)

# Disabling Weights and Biases logging
import os
os.environ["WANDB_DISABLED"] = "true"

trainer.train()

# Save the model
saved_model_path = "/content/finetuned_gpt2_model"
trainer.save_model(saved_model_path)

# Save the tokenizer
tokenizer.save_pretrained(saved_model_path)

"""**Exercise 11: Test Model with user input prompts**

- Create `generate_response()` function that takes a trained *model*, *tokenizer*, and a *prompt* string as input and generates a response using the GPT-2 model

- Test it with some user input prompts
"""

def generate_response(model, tokenizer, prompt, max_length=200):

    input_ids = tokenizer.encode(prompt, return_tensors="pt")      # 'pt' for returning pytorch tensor

    # Check the device of the model
    device = next(model.parameters()).device

    # Move input_ids to the same device as the model
    input_ids = input_ids.to(device)

    # Create the attention mask and pad token id
    attention_mask = torch.ones_like(input_ids)
    pad_token_id = tokenizer.eos_token_id

    output = model.generate(
        input_ids,
        max_length=max_length,
        num_return_sequences=1,
        attention_mask=attention_mask,
        pad_token_id=pad_token_id
    )

    return tokenizer.decode(output[0], skip_special_tokens=True)

# Load the fine-tuned model and tokenizer

my_model = GPT2LMHeadModel.from_pretrained(model_output_path)
my_tokenizer = GPT2Tokenizer.from_pretrained(model_output_path)

# Training sample question
train_ques[15]

# Training sample answer
train_ans[15]

# Response from model

prompt = "What is the outlook for Skin Cancer ?"
response = generate_response(my_model, my_tokenizer, prompt)
response

# Testing with given prompt 1

prompt = "What are the treatments for Skin Cancer?"
response = generate_response(my_model, my_tokenizer, prompt)
response

# Testing with given prompt 2

prompt = "What are the precautions for Skin Cancer?"
response = generate_response(my_model, my_tokenizer, prompt)
response

"""**Exercise 12: Compare the performance of a *GPT2 model* with the *GPT2 model fine-tuned* on MedQuAD data**

- Load another pre-trained GPT2LMHeadModel and do not fine-tune it

- To generate response using the untuned model, pass it as a parameter to `generate_response()` function

- Test both models (fine-tuned and untuned) with below user input prompts:

    - "What precautions to take for a healthy life?"
    - "What to do after being diagnosed with cancer?"
    - "What to do when feeling sick?"
"""

# Load a pre-trained GPT2 model, do not finetune it with MedQuAD data

untuned_model = GPT2LMHeadModel.from_pretrained("gpt2")

# Testing with finetuned model: prompt 1

prompt = "What precautions to take for a healthy life?"
response = generate_response(my_model, my_tokenizer, prompt)
response

# Testing with untuned model: prompt 1

prompt = "What precautions to take for a healthy life?"
response = generate_response(untuned_model, my_tokenizer, prompt)
response

# Testing with finetuned model: prompt 2

prompt = "What to do after being diagnosed with cancer?"
response = generate_response(my_model, my_tokenizer, prompt)
response

# Testing with untuned model: prompt 2

prompt = "What to do after being diagnosed with cancer?"
response = generate_response(untuned_model, my_tokenizer, prompt)
response

# Testing with finetuned model: prompt 3

prompt = "What to do when feeling sick?"
response = generate_response(my_model, my_tokenizer, prompt)
response

# Testing with untuned model: prompt 3

prompt = "What to do when feeling sick?"
response = generate_response(untuned_model, my_tokenizer, prompt)
response

"""## Push your model to Hugging Face Model Hub

**Exercise 13: Follow below steps to push your fine-tuned model to HuggingFace Model Hub [4 Marks]**

1. [Sign up](https://huggingface.co/join) for a Hugging Face account
2. Create an access token for your account and save it
3. Store your access token in the Hugging Face cache folder within colab
4. Push your fine-tuned model and tokenizer to Model Hub
5. Load the model back from Hub and test it with user input prompts

* **Create an access token for your account**

    Once you have an account, to create an access token:
    
    - Go to your `Settings`, then click on the `Access Tokens` tab. Click on the `New token` button to create a new User Access Token.
    - Select a Token type as `Write` and give a name for your token
    - Click on Create token
    - Once a token is created save it somewhere
    - When required later, use the old saved token or create a new token again

    To know more about Access Tokens, refer [here](https://huggingface.co/docs/hub/security-tokens).

* **Store your access token in the Hugging Face cache folder within colab**

    Once you have your User Access Token, run the following command to authenticate your identity to the Hub.
    - `!huggingface-cli login`
    - Paste your Access token when prompted
    - Type **n** when prompted to Add token as git credential? (Y/n)

    For more details on login, refer [here](https://huggingface.co/docs/huggingface_hub/quick-start#login).
"""

!huggingface-cli login

"""* **Push your fine-tuned model and tokenizer to Model Hub**

    - Use `push_to_hub()` method of your model and tokenizer both, to push them on hub
    - Specify name for your repository where the model and tokenizer will be pushed using `repo_id` parameter
    - Push model and tokenizer to the same repository

    - **Hint:**

        - Use `push_to_hub()` method of your model. For parameter details, refer [here](https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.push_to_hub).
        - Use `push_to_hub()` method of your tokenizer. For parameter details, refer [here](https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.push_to_hub).
        - Access your pushed model at `https://huggingface.co/[YOUR-USER-NAME]/[YOUR-MODEL-REPO-NAME]/tree/main`
"""

# Push model
my_repo = "medical-qa-gpt2"
model.push_to_hub(repo_id= my_repo, commit_message= "Upload fine-tuned model")

# Push tokenizer
tokenizer.push_to_hub(repo_id= my_repo, commit_message= "Upload tokenizer used")

"""Access your pushed model at `https://huggingface.co/[YOUR-USER-NAME]/[YOUR-MODEL-REPO-NAME]/tree/main`

For example: https://huggingface.co/yrajm1997/medical-qa-gpt2/tree/main

* **Load the model and tokenizer back from Hub and test it with user input prompts**

    - In many cases, the architecture you want to use can be guessed from the name or the path of the pretrained model you are supplying to the `from_pretrained()` method. **AutoClasses** can be used to automatically retrieve the relevant model given the name/path to the pretrained weights/config/vocabulary.

    - Instantiating one of `AutoConfig`, `AutoModel`, and `AutoTokenizer` will directly create a class of the relevant architecture.

    - When the GPT2 Model transformer has a language modeling head on top, you can use an auto class with language modeling head on top as well - `AutoModelWithLMHead`.

    - Specify full path of your model repo i.e. ***''YOUR-USER-NAME/YOUR-REPO-NAME''*** while calling `from_pretrained()` method.
"""

from transformers import AutoModelWithLMHead, AutoTokenizer

# Load your model from hub
loaded_model = AutoModelWithLMHead.from_pretrained("yrajm1997/medical-qa-gpt2")

# Load your tokenizer from hub
loaded_tokenizer = AutoTokenizer.from_pretrained("yrajm1997/medical-qa-gpt2")

# Response from loaded model

prompt = "What is the outlook for Skin Cancer ?"
response = generate_response(loaded_model, loaded_tokenizer, prompt)
response

"""## Gradio Implementation

Gradio is an open-source python library that allows us to quickly create easy-to-use, customizable UI components for our ML model, any API, or any arbitrary function in just a few lines of code. We can integrate the GUI directly into the Python notebook, or we can share the link with anyone.

**Exercise 14: Create a Gradio app for your fine-tuned model pushed on Hugging Face Model Hub [2 Marks]**

- Install and import `gradio` library
- Create a function to use your fine-tuned model for response generation
    - Use the model and tokenizer directly within the function, do not pass them as parameters
    - Function should take input prompt text, and max response length as its input parameters
    - Function should output the generated response text
- Create input and output gradio elements
- Create a gradio interface object
- Launch the interface to generate UI
"""

!pip -q install gradio

import gradio

# Function for response generation

def generate_query_response(prompt, max_length=200):

    model = loaded_model
    tokenizer = loaded_tokenizer

    input_ids = tokenizer.encode(prompt, return_tensors="pt")

    # Create the attention mask and pad token id
    attention_mask = torch.ones_like(input_ids)
    pad_token_id = tokenizer.eos_token_id

    output = model.generate(
        input_ids,
        max_length=max_length,
        num_return_sequences=1,
        attention_mask=attention_mask,
        pad_token_id=pad_token_id
    )

    return tokenizer.decode(output[0], skip_special_tokens=True)

# Input from user
in_prompt = gradio.inputs.Textbox(lines=10, placeholder=None, default="question", label='Enter Medical-Query')
in_max_length = gradio.inputs.Number(label='Enter Max Response Length', optional=True)

# Output response
out_response = gradio.outputs.Textbox(type="text", label='Response')

# Gradio interface to generate UI link
iface = gradio.Interface(fn = generate_query_response,
                         inputs = [in_prompt, in_max_length],
                         outputs = [out_response],
                         title = 'Medical Q&A',
                         description = 'finetuned GPT2 model',
                         allow_flagging = 'never')

iface.launch(share = True)

"""## Upload your Gradio application on Hugging Face Spaces

**Exercise 15: Upload your Gradio application on Hugging Face Spaces [4 Marks]**

1. Start a new Hugging Face Space by going to your profile and [clicking "New Space"](https://huggingface.co/new-space)

2. Provide details for your space:
    - Space name
    - License (eg. [MIT](https://opensource.org/licenses/MIT))
    - Space SDK (software development kit) (eg. `Gradio`)
    - Space hardware (CPU basic)
    - Choose whether your Space is public or private
    - Click "Create Space"

3. Go to ***Add files -> Create a new file*** option to add below files:
    - `requirements.txt`: should contain the dependencies to run your app such as transformers, torch and gradio
    - `app.py`: should contain steps to
        - import required packages
        - load your fine-tuned model and tokenizer from the Model Hub
        - function to use your fine-tuned model for response generation
        - create input and output gradio elements
        - create a gradio inference object
        - launch the interface to generate UI

4. Access the `App` tab of your repository to see the build progress (debug if error persists)

5. Once the app has built successfully, test the application running on your Space with a user input prompt

**Solution:**

- Files used `requirements.txt` and `app.py` are kept in the drive.

- Access the app: https://huggingface.co/spaces/yrajm1997/medical-qa-app
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# transformers
# torch
# gradio

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import transformers
# import torch
# import gradio
# 
# from transformers import AutoModelWithLMHead, AutoTokenizer
# 
# # Load your model from hub
# loaded_model = AutoModelWithLMHead.from_pretrained("yrajm1997/medical-qa-gpt2")
# 
# # Load your tokenizer from hub
# loaded_tokenizer = AutoTokenizer.from_pretrained("yrajm1997/medical-qa-gpt2")
# 
# # Function for response generation
# def generate_query_response(prompt, max_length=200):
#     model = loaded_model
#     tokenizer = loaded_tokenizer
# 
#     input_ids = tokenizer.encode(prompt, return_tensors="pt")
# 
#     # Create the attention mask and pad token id
#     attention_mask = torch.ones_like(input_ids)
#     pad_token_id = tokenizer.eos_token_id
# 
#     output = model.generate(
#         input_ids,
#         max_length=max_length,
#         num_return_sequences=1,
#         attention_mask=attention_mask,
#         pad_token_id=pad_token_id
#     )
#     return tokenizer.decode(output[0], skip_special_tokens=True)
# 
# 
# # Input from user
# in_prompt = gradio.inputs.Textbox(lines=10, placeholder=None, default="question", label='Enter Medical-Query')
# in_max_length = gradio.inputs.Number(label='Enter Max Response Length', optional=True)
# M6_SNB_MiniProject_1_PartA_Medical_Q&A_GPT2.ipynb
# # Output response
# out_response = gradio.outputs.Textbox(type="text", label='Response')
# 
# # Gradio interface to generate UI link
# iface = gradio.Interface(fn = generate_query_response,
#                          inputs = [in_prompt, in_max_length],
#                          outputs = [out_response],
#                          title = 'Medical Q&A',
#                          description = 'finetuned GPT2 model',
#                          allow_flagging = 'never')
# 
# iface.launch()